/**
 * Project and Story Brief type definitions
 * These types define the core data structures for the Launch Video Studio
 */

import type { Message } from './chat';

// ============================================================================
// Phase 3: Storyboard Types
// ============================================================================

/**
 * Camera movement types for scenes
 */
export type CameraMovement =
  | 'static'
  | 'pan-left'
  | 'pan-right'
  | 'tilt-up'
  | 'tilt-down'
  | 'zoom-in'
  | 'zoom-out'
  | 'dolly-in'
  | 'dolly-out'
  | 'tracking'
  | 'crane'
  | 'handheld';

/**
 * Shot type/framing
 */
export type ShotType =
  | 'extreme-wide'
  | 'wide'
  | 'medium-wide'
  | 'medium'
  | 'medium-close'
  | 'close-up'
  | 'extreme-close'
  | 'over-shoulder'
  | 'pov';

/**
 * Transition type between scenes
 */
export type TransitionType =
  | 'cut'
  | 'fade'
  | 'dissolve'
  | 'wipe'
  | 'morph'
  | 'match-cut'
  | 'j-cut'
  | 'l-cut';

/**
 * A single scene in the storyboard
 */
export interface StoryboardScene {
  /** Unique identifier */
  id: string;
  /** Scene order (1-indexed) */
  order: number;
  /** Visual description - what we see */
  visualDescription: string;
  /** Camera framing/shot type */
  shotType: ShotType;
  /** Camera movement during the scene */
  cameraMovement: CameraMovement;
  /** Duration in seconds */
  duration: number;
  /** Voiceover script for this scene */
  voiceover: string;
  /** On-screen text/titles (optional) */
  onScreenText?: string;
  /** Transition to next scene */
  transition: TransitionType;
  /** Additional notes for production */
  notes?: string;
  /** Rough sketch/wireframe URL (generated in Phase 3) */
  sketchUrl?: string;
  /** Generated image URL (filled in Phase 4) */
  imageUrl?: string;
  /** Generated video URL (filled in Phase 5) */
  videoUrl?: string;
}

/**
 * Complete storyboard for a project
 */
export interface Storyboard {
  /** All scenes in order */
  scenes: StoryboardScene[];
  /** Target total duration in seconds */
  targetDuration: 30 | 60 | 90;
  /** Overall pacing notes */
  pacingNotes: string;
  /** Music/audio direction */
  audioDirection: string;
  /** Generated by AI or manually created */
  generatedAt?: string;
  /** Model used for generation */
  generatedBy?: string;
}

/**
 * Default empty storyboard
 */
export const DEFAULT_STORYBOARD: Storyboard = {
  scenes: [],
  targetDuration: 60,
  pacingNotes: '',
  audioDirection: '',
};

/**
 * A generated keyframe image for a scene
 */
export interface KeyframeImage {
  /** Unique identifier */
  id: string;
  /** Associated scene ID */
  sceneId: string;
  /** Scene order (for reference) */
  sceneOrder: number;
  /** URL to the generated image */
  imageUrl: string;
  /** The prompt used to generate this image */
  prompt: string;
  /** Whether this is the approved/selected image */
  isApproved: boolean;
  /** Generation timestamp */
  generatedAt: string;
}

/**
 * Keyframes data for Phase 4
 */
export interface KeyframesData {
  /** All generated keyframe images */
  images: KeyframeImage[];
  /** Last generation timestamp */
  lastGeneratedAt?: string;
}

/**
 * Default empty keyframes
 */
export const DEFAULT_KEYFRAMES: KeyframesData = {
  images: [],
};

// ============================================================================
// Phase 5: Video Clips Types
// ============================================================================

/**
 * A generated video clip for a scene
 */
export interface VideoClip {
  /** Unique identifier */
  id: string;
  /** Associated scene ID */
  sceneId: string;
  /** Scene order (for reference) */
  sceneOrder: number;
  /** URL to the generated video */
  videoUrl: string;
  /** The source keyframe image used */
  sourceImageUrl: string;
  /** The prompt used to generate this video */
  prompt: string;
  /** Duration in seconds */
  duration: number;
  /** Whether this is the approved/selected video */
  isApproved: boolean;
  /** Generation timestamp */
  generatedAt: string;
  /** Generation status */
  status: 'pending' | 'generating' | 'completed' | 'failed';
  /** Error message if failed */
  error?: string;
}

/**
 * Video clips data for Phase 5
 */
export interface VideoClipsData {
  /** All generated video clips */
  clips: VideoClip[];
  /** Last generation timestamp */
  lastGeneratedAt?: string;
}

/**
 * Default empty video clips
 */
export const DEFAULT_VIDEO_CLIPS: VideoClipsData = {
  clips: [],
};

/**
 * Check if video clips phase is complete (all scenes have approved videos)
 */
export function isVideoClipsComplete(
  videoClips: VideoClipsData | null,
  storyboard: Storyboard | null
): boolean {
  if (!videoClips || !storyboard) return false;
  if (storyboard.scenes.length === 0) return false;

  // Check each scene has at least one approved video
  for (const scene of storyboard.scenes) {
    const hasApproved = videoClips.clips.some(
      (clip) => clip.sceneId === scene.id && clip.isApproved && clip.status === 'completed'
    );
    if (!hasApproved) return false;
  }
  return true;
}

/**
 * Check if keyframes phase is complete (all scenes have approved images)
 */
export function isKeyframesComplete(
  keyframes: KeyframesData | null,
  storyboard: Storyboard | null
): boolean {
  if (!keyframes || !storyboard) return false;
  if (storyboard.scenes.length === 0) return false;

  // Check each scene has at least one approved image
  for (const scene of storyboard.scenes) {
    const hasApproved = keyframes.images.some(
      (img) => img.sceneId === scene.id && img.isApproved
    );
    if (!hasApproved) return false;
  }
  return true;
}

/**
 * Shot type display labels
 */
export const SHOT_TYPE_LABELS: Record<ShotType, string> = {
  'extreme-wide': 'Extreme Wide',
  'wide': 'Wide Shot',
  'medium-wide': 'Medium Wide',
  'medium': 'Medium Shot',
  'medium-close': 'Medium Close-up',
  'close-up': 'Close-up',
  'extreme-close': 'Extreme Close-up',
  'over-shoulder': 'Over the Shoulder',
  'pov': 'POV',
};

/**
 * Camera movement display labels
 */
export const CAMERA_MOVEMENT_LABELS: Record<CameraMovement, string> = {
  'static': 'Static',
  'pan-left': 'Pan Left',
  'pan-right': 'Pan Right',
  'tilt-up': 'Tilt Up',
  'tilt-down': 'Tilt Down',
  'zoom-in': 'Zoom In',
  'zoom-out': 'Zoom Out',
  'dolly-in': 'Dolly In',
  'dolly-out': 'Dolly Out',
  'tracking': 'Tracking',
  'crane': 'Crane',
  'handheld': 'Handheld',
};

/**
 * Transition type display labels
 */
export const TRANSITION_TYPE_LABELS: Record<TransitionType, string> = {
  'cut': 'Cut',
  'fade': 'Fade',
  'dissolve': 'Dissolve',
  'wipe': 'Wipe',
  'morph': 'Morph',
  'match-cut': 'Match Cut',
  'j-cut': 'J-Cut',
  'l-cut': 'L-Cut',
};

/**
 * Check if a storyboard is complete enough to proceed
 */
export function isStoryboardComplete(storyboard: Storyboard | null): boolean {
  if (!storyboard) return false;
  if (storyboard.scenes.length === 0) return false;

  // Check that total duration is close to target
  const totalDuration = storyboard.scenes.reduce((sum, s) => sum + s.duration, 0);
  const minDuration = storyboard.targetDuration * 0.8;
  const maxDuration = storyboard.targetDuration * 1.2;

  return totalDuration >= minDuration && totalDuration <= maxDuration;
}

// ============================================================================
// Phase 2: Style Guide Types
// ============================================================================

/**
 * Reference video metadata (simplified - analysis goes into categories)
 */
export interface ReferenceVideo {
  id: string;
  url: string;
  title: string;
  model: string;
  analyzedAt: string;
}

/**
 * A single insight bullet point extracted from a video
 */
export interface StyleInsight {
  id: string;
  text: string;
  videoId: string;
  videoTitle: string;
}

/**
 * The 6 style category keys
 */
export type StyleCategoryKey =
  | 'colorPalette'
  | 'typographyStyle'
  | 'motionDesign'
  | 'pacingRhythm'
  | 'visualMetaphors'
  | 'transitionStyles';

/**
 * A style category with its insights
 */
export interface StyleCategory {
  label: string;
  description: string;
  insights: StyleInsight[];
}

/**
 * All 6 style categories
 */
export type StyleCategories = Record<StyleCategoryKey, StyleCategory>;

/**
 * Lighting style options
 */
export type LightingStyle =
  | 'soft-natural'
  | 'dramatic-contrast'
  | 'cinematic'
  | 'high-key'
  | 'low-key';

/**
 * Camera style options
 */
export type CameraStyle =
  | 'intimate'
  | 'documentary'
  | 'cinematic'
  | 'commercial';

/**
 * Style Guide - The output of Phase 2 Style
 * Contains visual direction for the video
 */
export interface StyleGuide {
  /** Reference videos that have been analyzed */
  referenceVideos: ReferenceVideo[];
  /** The 6 style categories with insights from all videos */
  categories: StyleCategories;
  /** Overall mood/tone */
  mood: string;
  /** Lighting style */
  lighting: LightingStyle;
  /** Camera style */
  cameraStyle: CameraStyle;
  /** Additional notes */
  additionalNotes: string;
}

/**
 * Project status representing the current phase in the pipeline
 */
export type ProjectStatus =
  | 'discover'
  | 'style'
  | 'storyboard'
  | 'images'
  | 'videos'
  | 'stitch'
  | 'audio'
  | 'complete';

/**
 * Story Brief - The output of Phase 1 Discovery
 * Contains the emotional core and narrative elements extracted from the interview
 */
export interface StoryBrief {
  /** Company name */
  companyName: string;

  /** Company tagline or one-liner */
  tagline: string;

  /** Raw, visceral description of the problem being solved */
  pain: string;

  /** What the product/service changes for the user */
  solution: string;

  /** The before state → after state transformation */
  transformation: string;

  /** Who suffers, who triumphs, why it matters */
  emotionalStakes: string;

  /** What makes this story worth telling */
  uniqueAngle: string;

  /**
   * Emotional behaviors - actions that show emotion rather than tell
   * Examples:
   * - "she refreshes the dashboard for the fifth time"
   * - "he closes the laptop slowly, staring at nothing"
   * - "they lean forward when the notification appears"
   */
  emotionalBehaviors: string[];

  /**
   * Tone notes - guiding mood phrases for the entire video
   * Examples:
   * - "quiet confidence building under chaos"
   * - "hope mixed with exhaustion"
   * - "a world where small wins feel huge"
   */
  toneNotes: string[];

  /** Complete interview transcript */
  interviewTranscript: Message[];
}

/**
 * Project - The main entity representing a video project
 */
export interface Project {
  /** Unique identifier (UUID) */
  id: string;

  /** Project/company name */
  name: string;

  /** Current phase in the pipeline */
  status: ProjectStatus;

  /** When the project was created */
  createdAt: string;

  /** When the project was last modified */
  updatedAt: string;

  /** Story Brief from Phase 1 Discovery (null until generated) */
  storyBrief: StoryBrief | null;

  /** Style Guide from Phase 2 Style (null until created) */
  styleGuide: StyleGuide | null;

  /** Storyboard from Phase 3 (null until created) */
  storyboard: Storyboard | null;

  /** Keyframes from Phase 4 (null until created) */
  keyframes: KeyframesData | null;

  /** Video clips from Phase 5 (null until created) */
  videoClips: VideoClipsData | null;

  /** Chat history for the discovery phase */
  chatHistory: Message[];
}

/**
 * Project metadata for list views (lighter weight than full Project)
 */
export interface ProjectSummary {
  id: string;
  name: string;
  status: ProjectStatus;
  createdAt: string;
  updatedAt: string;
  tagline: string | null;
  hasStoryBrief: boolean;
}

/**
 * Input for creating a new project
 */
export interface CreateProjectInput {
  name: string;
  tagline: string;
}

/**
 * Phase metadata for display in the stepper
 */
export interface PhaseInfo {
  id: ProjectStatus;
  name: string;
  description: string;
  order: number;
}

/**
 * All phases in order
 */
export const PHASES: PhaseInfo[] = [
  { id: 'discover', name: 'Discover', description: 'Extract the emotional story', order: 1 },
  { id: 'style', name: 'Style', description: 'Define visual direction', order: 2 },
  { id: 'storyboard', name: 'Storyboard', description: 'Plan scenes and shots', order: 3 },
  { id: 'images', name: 'Images', description: 'Generate keyframes', order: 4 },
  { id: 'videos', name: 'Videos', description: 'Animate scenes', order: 5 },
  { id: 'stitch', name: 'Stitch', description: 'Assemble timeline', order: 6 },
  { id: 'audio', name: 'Audio', description: 'Add voice and music', order: 7 },
  { id: 'complete', name: 'Complete', description: 'Export final video', order: 8 },
];

/**
 * Get phase info by status
 */
export function getPhaseInfo(status: ProjectStatus): PhaseInfo {
  const phase = PHASES.find(p => p.id === status);
  if (!phase) {
    throw new Error(`Unknown phase status: ${status}`);
  }
  return phase;
}

/**
 * Get the next phase after the current one
 */
export function getNextPhase(current: ProjectStatus): ProjectStatus | null {
  const currentPhase = getPhaseInfo(current);
  const nextPhase = PHASES.find(p => p.order === currentPhase.order + 1);
  return nextPhase?.id ?? null;
}

/**
 * Check if a phase is complete (has passed)
 */
export function isPhaseComplete(current: ProjectStatus, target: ProjectStatus): boolean {
  const currentPhase = getPhaseInfo(current);
  const targetPhase = getPhaseInfo(target);
  return currentPhase.order > targetPhase.order;
}

// ============================================================================
// Style Guide Helpers
// ============================================================================

/**
 * Default style categories with labels and descriptions
 */
export const DEFAULT_STYLE_CATEGORIES: StyleCategories = {
  colorPalette: {
    label: 'Color Palette',
    description: 'Colors, grading, tones, and visual temperature',
    insights: [],
  },
  typographyStyle: {
    label: 'Typography Style',
    description: 'Fonts, text treatment, titles, and captions',
    insights: [],
  },
  motionDesign: {
    label: 'Motion Design',
    description: 'How elements move, animations, and kinetic energy',
    insights: [],
  },
  pacingRhythm: {
    label: 'Pacing & Rhythm',
    description: 'Edit timing, cuts, tempo, and flow',
    insights: [],
  },
  visualMetaphors: {
    label: 'Visual Metaphors',
    description: 'Symbolic imagery, storytelling devices, and meaning',
    insights: [],
  },
  transitionStyles: {
    label: 'Transition Styles',
    description: 'How scenes connect, cuts, fades, and wipes',
    insights: [],
  },
};

/**
 * Default empty style guide
 */
export const DEFAULT_STYLE_GUIDE: StyleGuide = {
  referenceVideos: [],
  categories: DEFAULT_STYLE_CATEGORIES,
  mood: '',
  lighting: 'cinematic',
  cameraStyle: 'cinematic',
  additionalNotes: '',
};

/**
 * Mood options for selection
 */
export const MOOD_OPTIONS = [
  'Hopeful & Inspiring',
  'Professional & Confident',
  'Warm & Friendly',
  'Bold & Energetic',
  'Calm & Reassuring',
  'Urgent & Compelling',
  'Playful & Creative',
  'Sophisticated & Premium',
] as const;

/**
 * Lighting style display names
 */
export const LIGHTING_LABELS: Record<LightingStyle, string> = {
  'soft-natural': 'Soft Natural',
  'dramatic-contrast': 'Dramatic Contrast',
  'cinematic': 'Cinematic',
  'high-key': 'High-Key (Bright)',
  'low-key': 'Low-Key (Moody)',
};

/**
 * Camera style display names
 */
export const CAMERA_STYLE_LABELS: Record<CameraStyle, string> = {
  'intimate': 'Intimate & Personal',
  'documentary': 'Documentary',
  'cinematic': 'Cinematic',
  'commercial': 'Commercial',
};

/**
 * Check if a style guide is complete enough to proceed
 */
export function isStyleGuideComplete(styleGuide: StyleGuide | null): boolean {
  if (!styleGuide) return false;

  // Minimum requirements:
  // 1. Mood selected
  // 2. Lighting style set
  return (
    styleGuide.mood.length > 0 &&
    styleGuide.lighting.length > 0
  );
}
